### ISSUE TITLE
Charmap error

### ISSUE THREAD

**Issue by Thurgon** [rustyinfinity/StashNfoExporter#8]
2024-03-25 09:53:58
Error   
Scene.Update.Post [Stash NFO Exporter]: returned error: exit status 1
2024-03-25 09:53:58
Error   
[Plugin / Stash NFO Exporter] UnicodeEncodeError: 'charmap' codec can't encode character '\xe8' in position 37: character maps to <undefined>
2024-03-25 09:53:58
Error   
[Plugin / Stash NFO Exporter]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-25 09:53:58
Error   
[Plugin / Stash NFO Exporter]     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
2024-03-25 09:53:58
Error   
[Plugin / Stash NFO Exporter]   File "PATH\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1250.py", line 19, in encode
2024-03-25 09:53:58
Error   
[Plugin / Stash NFO Exporter]     print("Changes Detected Adding to Database" +scene['title'] )
2024-03-25 09:53:58
Error   
[Plugin / Stash NFO Exporter]   File "PATH\.stash\plugins\StashNfoExporter-main/StashNfoExporter.py", line 255, in <module>
2024-03-25 09:53:58
Error   
[Plugin / Stash NFO Exporter] Traceback (most recent call last):

**Comment by Thurgon** [comment]
With latest version I'm getting error. I'm running stash on Win11 as admin.

```python
Error running plugin task: error running plugin: exec: "C:\\Users\\Petr\\.stash\\plugins\\StashNfoExporter-main\\C:\\Users\\Petr\\.stash\\plugins\\StashNfoExporter-main\\python3": file does not exist
```
